### ISSUE TITLE
GameController is sometimes repeatedly swaping from/to READY/INITIAL

### ISSUE THREAD

**Issue by omichel** [RoboCup-Humanoid-TC/GameController#149]
When I am running the GameController on some machines (in particular on a Windows machine), I am getting a strange bug: the GameController suddently keeps sending READY and INITIAL message repeatedly. It is however not 100% reproducible but occurs quite often (more than 50% of the cases) on my machine. Unfortunately, this is causing the tests to fail slowing down the development of the referee. Meanwhile, I will switch to Linux where the bug doesn't seem to occur so far.

I am attaching the output log when running the `game_phases/dropped_ball` test.
[output.txt](https://github.com/RoboCup-Humanoid-TC/GameController/files/6452268/output.txt)

**Comment by medrimonia** [comment]
From various RoboCup experience, this kind of bug is very often related to the presence of another GameController running on the same network (since it uses UDP broadcast). In most of our team code, we implemented safe guards to show warnings when there are messages received from two different IPs.

**Comment by omichel** [comment]
OK, thank you, I will double check it.

**Comment by omichel** [comment]
That indeed explains many of the headaches I was having because I was running the tests on several machines on the local network here, and they were randomly failing because of this... I shall probably fix the referee to drop UDP packets coming from a different IP address to avoid this problem in the future...

**Comment by medrimonia** [comment]
One of the option that might happen is that the interface used is the one from WiFi if your computer is connected through both ethernet and WiFi. Otherwise, I'm not sure of where the issue could come...

**Comment by omichel** [comment]
I ruled out this by disabling the wifi interface, but the problem remains. It seem UDP broadcast computes a special IP address based on the local IP and broadcast mask... Not sure yet about the details... I will continue to investigate.
